### ISSUE TITLE
Income and Expenses

### ISSUE THREAD

**Issue by Samet91** [Samet91/capstone-project#5]

**Comment by Samet91** [comment]
## Value Preposition
As a User
I need to see my Income and Expenses

## Description
![Bildschirmfoto 2021-11-20 um 19 18 21](https://user-images.githubusercontent.com/91253457/142766091-0428013c-95ed-4540-a225-84d82538109f.png)

## Acceptance Criteria
- [ ] if no expenses and income were written then 0 must be stand
- [ ] € must be in front of the number
- [ ] income  field must not be entered below 0
- [ ] numbers must always be centered

## Tasks
- [ ] create component incomeExpenseBox
- [ ] numbers position always center
