### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by Samet91** [Samet91/capstone-project#6]

**Comment by Samet91** [comment]
## Value Preposition
As a User 
I need the overview

## Description
![Bildschirmfoto 2021-11-20 um 19 18 28](https://user-images.githubusercontent.com/91253457/142766913-41214743-2705-4e72-b21c-c80a64213ef3.png)

## Acceptance Criteria
- [ ] After click: show all transactions among each other
- [ ] The transaction should never overlap in the list
- [ ] The transaction should after 8 items scroll vertically on overflow

## Tasks
- [ ] Create feature branch
- [ ] Create ol-list Transactionlist
- [ ] Integrate component into App
