### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by Samet91** [Samet91/capstone-project#7]

**Comment by Samet91** [comment]
## Value Preposition
As a User 
i need two inputs for Income and Expense

## Description
![Bildschirmfoto 2021-11-20 um 19 18 35](https://user-images.githubusercontent.com/91253457/142768774-86f2cb4b-d26e-4b4b-8bce-d6698bd8533f.png)

## Acceptance Criteria
- [ ] Category-Input should only String
- [ ] max. 20 characters for Category
- [ ] Amount-Input should only Number
- [ ] max. 8 characters for Amount
- [ ] All inputs are `required` (browser shows warning if empty)
- [ ] After pressing the buttons set fields to empty

## Tasks
- [ ] create Transaction component
- [ ] create form , including 2x inputs/label and 2x submit buttons
- [ ]  input values shall be send to "Income-Expense and Balance" component
- [ ] Integrate component into App
