### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by Samet91** [Samet91/capstone-project#8]

**Comment by Samet91** [comment]
## Value Proposition
As a user
I need a Text and number Input
to be able to add my costs.

## Description
![Bildschirmfoto 2021-11-22 um 11 09 27](https://user-images.githubusercontent.com/91253457/142844147-752764ef-8aab-4257-b0b7-e9bf8232b0c4.png)

## Acceptance Criteria
- [ ] if no expenses and income were written then 0 must be stand
- [ ] All inputs are required (browser shows warning if empty)
- [ ] € must be in front of the number
- [ ] income field must not be entered below 0
- [ ] numbers must always be centered
- [ ] max. 20 characters for Category
- [ ] max. 10 characters for amount
  
## Tasks
- [ ]  create component incomeExpenseBox
- [ ] create component Inputs
- [ ] create component Button
- [ ] Form component
- [ ] Integrate components into App
- [ ] Setup deployment
